### ISSUE TITLE
Invalid dom generated

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#503]
Seems like the MarkdownViewer creates some issues of invalid dom

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:56:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:56:76)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:56:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:56:76)
    at MarkdownViewer (webpack-internal:///./components/MarkdownViewer.tsx:34:11)
    at p
```

**Comment by ismailToyran** [comment]
Should be fixed with https://github.com/liteflow-labs/starter-kit/pull/507
