### ISSUE TITLE
Issue when accepting an ERC1155 offer: SafeMath: subtraction overflow

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#53]
When accepting a listed offer from [this NFT](https://hodooi-bsc-testnet-hodooi.vercel.app/tokens/82153703594476779040147787829905511244693377253089154907242808064142243563523) the transaction cannot be send and return the following error:

`execution reverted: SafeMath: subtraction overflow`

Can be reproduced on this offer https://hodooi-bsc-testnet-hodooi.vercel.app/checkout/8990f408-12a0-4907-a010-6394929fdfe9

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: SafeMath: subtraction overflow", method="estimateGas", transaction={"from":"0xB5a15932Be6caEeF5d21AC704300bd45e10ff92d","to":"0x23642f6b345af0999A636d7d749a8D7A48355bDf","data":"0xe99a3f800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000044000000000000000000000000000000000000000000000000000000000000004c000000000000000000000000000000000000000000000000000000000000008400000000000000000000000004b595014f7b45789c3f4e79324ae6d8090a6c8b50000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000c124187733baa516d864a21e2174bd99c1652f3967eaab7aadb21464e6c965500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062a9bfa94c2342660000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001973bb640000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004000000000000000000000000008e5d5aceeab15a15b060901e539d15f0747f017b5a15932be6caeef5d21ac704300bd45e10ff92d16477607997706991990880300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000001bc16d674ec800008ae85d840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bfb59b6b71ad1f546f800b5ed706ff1dc99c689500000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e572bd13dfb84fae4f42ef9429fd24e7725e93f500000000000000000000000000000000000000000000000000000000000000fa0000000000000000000000000000000000000000000000000000000000000041d9bb8eed080d1487f3eb268983cd46c5145530952410a8b8cf938fa629d4984b05b08475c526e8df6826670b8aa3926d00271770c86b635f25651824fc06bf331b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000b5a15932be6caeef5d21ac704300bd45e10ff92d00000000000000000000000000000000000000000000000000000000000001200000000000000000000000004b595014f7b45789c3f4e79324ae6d8090a6c8b500000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062a9bfa94c2342660000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000001bc16d674ec800008ae85d840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bfb59b6b71ad1f546f800b5ed706ff1dc99c689500000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001973bb640000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004000000000000000000000000008e5d5aceeab15a15b060901e539d15f0747f017b5a15932be6caeef5d21ac704300bd45e10ff92d16477607997706991990880300000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: SafeMath: subtraction overflow","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e536166654d6174683a207375627472616374696f6e206f766572666c6f770000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: SafeMath: subtraction overflow\",\n    \"data\": \"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e536166654d6174683a207375627472616374696f6e206f766572666c6f770000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:27:365128)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:27:368078)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:27:368688)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:108855)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:109887\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:19:40881\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:27:365128)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:27:368078)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:27:368688)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:108855)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:109887\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:19:40881"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)
```

**Comment by EmmanuelDrouin** [comment]
@antho1404 is this issue still relevant? Is it an issue on a specific token or something more general?
